### ISSUE TITLE
TypedDict

### ISSUE THREAD

**Issue by ltworf** [ltworf/typedload#100]
> A dictionary type with per-key types. See PEP 589 and typing.TypedDict. TypedDict uses only string keys. By default, every key is required to be present. Specify “total=False” to allow keys to be optional:

```python3
    class Location(TypedDict, total=False):
        lat_long: tuple
        grid_square: str
        xy_coordinate: tuple
```

**Comment by kkom** [comment]
Hey @ltworf – I think that https://github.com/ltworf/typedload/pull/108 did not bring support for `total=False` config.

Would that be difficult to add? I'm happy to submit a PR, but I would appreciate some tips (if you have any here!)

Thanks!

Konrad

**Comment by ltworf** [comment]
@kkom not very difficult it seems :)

https://github.com/ltworf/typedload/pull/182

**Comment by kkom** [comment]
Amazing, thank you @ltworf !
