### ISSUE TITLE
AssertionError from typedload

### ISSUE THREAD

**Issue by Ploppz** [ltworf/typedload#111]
```
        try:
            return cast(T, func(self, value, type_))
        except Exception as e:
>           assert isinstance(e, TypedloadException)
E           AssertionError

../../../.local/lib/python3.8/site-packages/typedload/dataloader.py:236: AssertionError
```

I get this error in my application when calling `typedload.load` and I'm not sure what I should do about it - seems like that assert is there to catch a bug in typedload?

**Comment by Ploppz** [comment]
Update: I think I narrowed it down to using `datetime.datetime` as a type.
I had:
```
from datetime import datetime
# ...
class ApiJob(NamedTuple):
    # ...
    submit_date: datetime
    update_date: datetime
```

When I changed the `datetime`s to `str` it worked fine.

**Comment by ltworf** [comment]
Hi.

Thanks for your report.

The assertion error should definitely not happen and indicates a bug within the library itself.

The datetime loader/dumper uses lists. So something like this: `typedload.load([2019,11,11], datetime.date) `

I see that if I pass the wrong type of data it raises the assertion error you found so this is a valid bug. But I guess you were also calling it wrong :)

**Comment by Ploppz** [comment]
Thanks for the swift reply and explanation!
