### ISSUE TITLE
It seems that the new mypy doesn't type the load results as before.

### ISSUE THREAD

**Issue by ltworf** [ltworf/typedload#132]
Investigate and possibly fix.

**Comment by ltworf** [comment]
https://github.com/python/mypy/issues/8946

Seems mypy decided to change behaviour…

**Comment by ltworf** [comment]
```python3
from typing import *
T = TypeVar('T')

def create(t: Type[T]) -> T:
    ...

reveal_type(create(int))
reveal_type(create(str))
reveal_type(create(List[int]))
reveal_type(create(Dict[int, int]))
reveal_type(create(Tuple[int]))
reveal_type(create(Union[int,str]))
reveal_type(create(Optional[int]))
```

It actually never worked!

```
test.py:7: note: Revealed type is 'builtins.int*'
test.py:8: note: Revealed type is 'builtins.str*'
test.py:9: note: Revealed type is 'builtins.list*[builtins.int*]'
test.py:10: note: Revealed type is 'builtins.dict*[builtins.int*, builtins.int*]'
test.py:11: note: Revealed type is 'Any'
test.py:12: note: Revealed type is 'Any'
test.py:13: note: Revealed type is 'Any'
```

**Comment by thomascellerier** [comment]
Oh wow that breaks a lot of code.

**Comment by ltworf** [comment]
Well the new mypy rejects it completely instead of inferring Any, the old one only works for some types but not all, so the typechecking is not as strong as I thought.

**Comment by ltworf** [comment]
@thomascellerier I created an issue on mypy, let's see what they say about this. The good news is that if the top level is a dataclass or nameduple, it works :D

**Comment by ltworf** [comment]
Something seems to be moving https://github.com/python/mypy/issues/9773

**Comment by ltworf** [comment]
There is a PEP for review https://mail.python.org/archives/list/typing-sig@python.org/thread/7TDCBWT4RAYDJUQJ3B5NKXTQDUO5SIW2/

**Comment by ltworf** [comment]
Closing, since it has nothing to do with typedload
