### ISSUE TITLE
"Note that it is released with a GPL license and it cannot be used inside non GPL software."

### ISSUE THREAD

**Issue by marcj** [ltworf/typedload#139]
You wrote in your README

> Note that it is released with a GPL license and it cannot be used inside non GPL software.

What is your reason that your code under GPL can't be used in non-GPL software?

**Comment by marcj** [comment]
Oh, I misread, I thought it's LGPL. Time to remove this library. :)

**Comment by ltworf** [comment]
Well to be precise it can be used with non-GPL software, it just has the effect of making it GPL.

If you published it, too late…

**Comment by marcj** [comment]
No worries, I wanted to use it in a private project since I'm using it in a GPL-compatible OSS library already, but decided now to use something else and will probably also remove it from my OSS library since I don't like having multiple libraries doing the same thing. It's just kinda rare that people publish libraries as GPL especially something as simple as that. If you want to get more adoption of your library, you should probably switch to a MIT-like license.

**Comment by ltworf** [comment]
Eh, I know but spending my time to help proprietary software is very counter-productive.
