### ISSUE TITLE
Support typing.Any

### ISSUE THREAD

**Issue by phiresky** [ltworf/typedload#164]
I have some things that are a `Dict[str, Any]` where any can be any thing representable in json. So I basically want typeshed to "pass through" the values of that dict. I'm now using `Dict[str, Union[str, int, float, bool, NoneType]]` but to make it work recursively the type is even longer.

**Comment by ltworf** [comment]
Keep in mind that mypy won't support recursive types.

I've encountered situations where we needed to leave alone whatever type. Normally we implement a custom handler in this way:


```python

from typedload.dataloader import Loader

l = Loader()

l.handlers.append(
    (
        lambda t: t == Any,
        lambda _, v, __: v
    )
)
```

And then use that loader object.

```python
o = object()
l.load(o, Any) is o
```

I'm a bit unsure if I should implement this within typedload or not, since it seems to come up often. Maybe it could be a good idea to have it. I mostly didn't do it because of fear of unforseen drawbacks.

**Comment by thomascellerier** [comment]
How about adding an optional argument to the loader's constructor?
Something like this, equivalent to your snippet above:
```Python
from typedload.dataloader import Loader

l = Loader(passthrough_any=True)
```

The default would be "False" as today to stay strict by default.

**Comment by phiresky** [comment]
Yeah, that makes sense. Would be best if it also suggested doing that in the error message since it took me a bit to find the reason here (since my dict is hidden within a union so the error was more generic), but that might be hard to add.

My original code just had `info: dict` member btw, I only changed that to `info: Dict[str, Any]` since I thought that might be supported. Having `dict` might more explicitly mean "a dict of any serializeable stuff".

Another alternative would be to have typedload export a `Passthrough` type that can be used specifically to always mean passthrough.

**Comment by ltworf** [comment]
I'm not keen on exporting types because then mypy doesn't understand them, and I se mypy on every project where i use typedload

**Comment by ltworf** [comment]
But I think I will add the handler directly without extra options instead. I really can't see any reason why not, I was just being conservative towards the unforseen.

It is only needed for the loader, as the dumper always knows the actual type of the object it is dumping.
