### ISSUE TITLE
Support initvar

### ISSUE THREAD

**Issue by ltworf** [ltworf/typedload#185]
https://docs.python.org/3/library/dataclasses.html#post-init-processing

As suggested here: https://github.com/pappasam/serdelicacy#notes

**Comment by uyar** [comment]
If I'm not mistaken, this handles the parameters that are *not* supplied to `__init__`, but not the parameters that are *only* supplied to `__init__`. Here's a small example:

```python
from dataclasses import InitVar, dataclass, field
import typedload

@dataclass
class Foo:
    x: str
    y: str = field(init=False)

    def __post_init__(self):
        self.y = self.x.upper()

@dataclass
class Bar:
    x: InitVar[str] 
    y: str = field(init=False)

    def __post_init__(self, x):
        self.y = x.upper()

if __name__ == "__main__":
    foo = Foo(x="foo")
    print(foo)  # prints: Foo(x='foo', y='FOO')
    foo = typedload.load({"x": "foo"}, Foo)
    print(foo)  # prints: Foo(x='foo', y='FOO')

    bar = Bar(x="bar")
    print(bar)  # prints: Bar(y='BAR')
    bar = typedload.load({"x": "bar"}, Bar)
    print(bar)  # raises TypedLoadTypeError
```

Am I misinterpreting something here? What would be the recommended to handle this in typedload? A custom handler?

**Comment by uyar** [comment]
UPDATE: In my use case, I managed to handle it with a custom class and strconstructed.

**Comment by ltworf** [comment]
Yes you are correct. That is because I never needed them myself :)

I don't really understand the use case either… if you don't care about a value don't use it.

**Comment by uyar** [comment]
It helps if you want to set an attribute based on a parameter you don't want to save. Something like this:

```python
from dataclasses import InitVar, dataclass, field
from datetime import datetime
import typedload


@dataclass
class Person:
    age: InitVar[int]
    birth_year: int = field(init=False)

    def __post_init__(self, age):
        self.birth_year = datetime.now().year - age


if __name__ == "__main__":
    person = Person(age=30)
    print(person)   # prints: Person(birth_year=1993)
```
