### ISSUE TITLE
Undo v3

### ISSUE THREAD

**Issue by ltworf** [ltworf/typedload#199]
Version 3 exists solely for the deferred type evaluation feature of python 3.10.

However that change is for now being reverted, and pushed on to an unknown time in the future.

So it makes no sense to break API at this point. Revert the changes and make a 2.8 version instead.

**Comment by kkom** [comment]
Hey @ltworf – do you roughly know what is the timeline for this?

I'd like to start using https://github.com/ltworf/typedload/pull/206 in our project, but somehow depending on an unreleased version of this library in pipenv failed.

CC: @sid-at-github

**Comment by ltworf** [comment]
I missed that python had moved from alpha to beta, so I kept waiting for a newer python alpha -_-'

**Comment by ltworf** [comment]
Weeeell: `Error: Version 3.10.0b1 with arch x64 not found`

**Comment by kevinheavey** [comment]
Just wondering: would this v3 also allow us to use `from __future__ import annotations` on older Python versions?

**Comment by ltworf** [comment]
Yes, at the price of only being able to use module level type definitions, as anything else stops working.
