### ISSUE TITLE
Installing latest version fails due to missing README.md

### ISSUE THREAD

**Issue by patrickbucher** [ltworf/typedload#223]
```
$ python --version
Python 3.9.6
$ pip install --user typedload==2.9
ERROR: Command errored out with exit status 1:
     command: /tmp/foo/env/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-yxc_6q8g/typedload_4b5e1ebe723d4dd9b8e0d714eb344db6/setup.py'"'"'; __file__='"'"'/tmp/pip-install-yxc_6q8g/typedload_4b5e1ebe723d4dd9b8e0d714eb344db6/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ifve85qb                                          
         cwd: /tmp/pip-install-yxc_6q8g/typedload_4b5e1ebe723d4dd9b8e0d714eb344db6/                                            
    Complete output (5 lines):                                                                                                 
    Traceback (most recent call last):                                                                                         
      File "<string>", line 1, in <module>                                                                                     
      File "/tmp/pip-install-yxc_6q8g/typedload_4b5e1ebe723d4dd9b8e0d714eb344db6/setup.py", line 23, in <module>               
        with open('README.md', 'rt') as f:                                                                                     
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'                                                        
    ----------------------------------------            
```

**Comment by patrickbucher** [comment]
I see that there's a README, but is actually a link, which might cause the issue.

**Comment by ltworf** [comment]
Hi,

thanks for your report.

Which os are you using?

**Comment by patrickbucher** [comment]
Arch Linux, everything on latest.

**Comment by flaviojdz** [comment]
I am having the same issue compiling with pip tools.

ERROR: Command errored out with exit status 1:
       command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-resolver-7pnjbj5m/typedload/setup.py'"'"'; __file__='"'"'/tmp/pip-resolver-7pnjbj5m/typedload/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-iea1hgva
           cwd: /tmp/pip-resolver-7pnjbj5m/typedload/
      Complete output (5 lines):
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/tmp/pip-resolver-7pnjbj5m/typedload/setup.py", line 23, in <module>
          with open('README.md', 'rt') as f:
      FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
      ----------------------------------------
