### ISSUE TITLE
I'll give you €1000 to change the license to MIT or BSD

### ISSUE THREAD

**Issue by kevinheavey** [ltworf/typedload#232]
I'm working on an open source library and I don't want users of my library to have to worry about GPL. For what it's worth, I've wasted a few hours reading about GPL because of this library, even though the users of my code will likely all be other open source libraries.

I can give you €1000 via Liberapay if you change the license to MIT or BSD (I guess an equivalent to those two would be fine as well, they're just the ones I know).

If that's not enough money then no hard feelings, I'll just settle for using GPL in my library.

**Comment by kevinheavey** [comment]
Actually never mind lol, I just discovered apischema

**Comment by ltworf** [comment]
1. It is against the code of conduct of this project to complain against freedom.
2. apischema seems to be a really nice library, although still in beta
