### ISSUE TITLE
handle from __future__ import annotations / ForwardRefs better

### ISSUE THREAD

**Issue by phiresky** [ltworf/typedload#291]
Right now, typedload uses a custom implemented function to resolve forward refs (_forwardrefload). This function only works for a small amount of use cases.

This issue makes it kind of impossible to use typedload in files that have
`from __future__ import annotations`, which makes most type annotations into ForwardRefs. It's only going to get worse since these lazy-evaluated annotations are supposed to become standard in python 3.11 or something.

I don't know since when, but the official typing library has functions that resolve ForwardRefs correctly:

* `get_type_hints` resolves these correctly and can be used to get the type annotations of many things like NamedTuples, dataclasses
* `typing._eval_type` directly resolves a ForwardRef and is used by get_type_hints
* `ForwardRef._evaluate` is a member function of forwardref

`get_type_hints` is a publicly documented function, the others are internals i guess.

just doing `type_._evaluate(None, None, set())` in `_forwardrefload` seems to work in a tiny test but i don't know if it's correct.

**Comment by ltworf** [comment]
https://github.com/ltworf/typedload/pull/296

But it doesn't work with attrs, so I guess it could use some more work.

**Comment by ltworf** [comment]
I still think this is the way to go https://peps.python.org/pep-0649/ and they are incompatible, but this one is faster and can work with nested types.

So I can maybe make a temporary flag to enable forwardref stuff, since this other PEP seems to not be implemented, but it will be deprecated from day 1 and unsupported.

**Comment by ltworf** [comment]
> But it looks like if you use get_type_hints you won't get a problem either way

lol :)

The original one loses the context, so for anything that is not module level, it is impossible later on to go and "eval" because the context is simply lost forever and there is no way to get it back.

Which by the way implies that most of my test suite fails irreparably when that thing is enabled.

Which is why I think it's a terrible idea, since it's really really really not backwards compatible and there are no workarounds to make it compatible, except for putting everything top-level and manually fixing all the inevitable name collisions.

**Comment by phiresky** [comment]
Thanks for fixing the issue.

I'm not trying to be a dick here but I don't really understand why using get_type_hints is worse than not using it. You don't need to have pep563 enabled to use get_type_hints. get_type_hints is a no-op for non-forward type refs so everything stays the same except it also resolves most forward refs fine.  and it doesn't make anything worse other than that it resolves types that are explicitly forward refs, which you can't "correctly" resolve in any other way either until pep649 happens.

Looking at your test suite, with your new pep563=True flag force-enabled everywhere (but without from future import annotations) only 2 of 138 tests fail:

- *test_add_fref*: This one fails because you explicitly add a "fake" forward ref that is manually added to `frefs`. I don't understand why you would want to do this though - it seems better to just fix the type resolution by moving the type to not need a forward ref instead of having to remember to manually add it to the frefs array
- *test_known_refs*: This one only fails because I see you add your own "hacky" handling for forward refs: https://github.com/ltworf/typedload/blob/5e7ebfd9b6cc71b7d84d73b7c07af78bb1b22df7/typedload/dataloader.py#L275-L279
    That honestly doesn't really seem much better than what Pep563 does at all since it also interprets local definitions as completely global, which is very easy to break:
   ```py
    def test_collision(self):
        from typedload import dataloader

        class Tree1:
            class Node(NamedTuple):
                a: int
                next: Optional["Node"] = None

        class Tree2:
            class Node(NamedTuple):
                b: int
                next: Optional["Node"] = None

        loader = dataloader.Loader()
        print(loader.load({"a": 1, "next": {"a": 1}}, Tree1.Node))  # works
        print(loader.load({"b": 1, "next": {"b": 2}}, Tree2.Node))  # breaks unexpectedly, tries to construct the wrong Node type
   ```
   So really you get the same problem as you described pep563 has above:

   > [...] putting everything top-level and manually fixing all the inevitable name collisions.

   At least you should probably use `type_.__module__ + "." + type_.__qualname__` instead of `type_.__name__` in that code?

**Comment by ltworf** [comment]
True, but it's api breaking and requires a version bump, and since nobody has complained about this so far I think it's best to keep things as they are.
