### ISSUE TITLE
Forward reference typing hints support

### ISSUE THREAD

**Issue by hulucc** [ltworf/typedload#34]
TypeError: Cannot deal with value {'x': 5, 'y': 6, 'next': None} of type _ForwardRef('Node')
```
class Node(NamedTuple):
    x: int = 1
    y: int = 2
    next: 'Node' = None
```

**Comment by ltworf** [comment]
Yeah that isn't supported yet.

I'm not even sure of how to support it, because it needs to eval that string into a type.

The only sane solution I see, would be to pass a dictionary with `{'type': Type}` entries, but it wouldn't be so clean.

I'm open to suggestions.

**Comment by ltworf** [comment]
By the way, next should be `Optional[Node]` or your linked list can never end :)
