### ISSUE TITLE
License compatibility with MPL-2

### ISSUE THREAD

**Issue by d3dave** [ltworf/typedload#410]
Can typedload be used in a project licensed with Mozilla Public License 2.0 (MPL-2)?

**Comment by ltworf** [comment]
This seems to answer https://www.gnu.org/licenses/license-list.html#MPL-2.0

**Comment by d3dave** [comment]
> This seems to answer https://www.gnu.org/licenses/license-list.html#MPL-2.0

That only answers the opposite question of using an MPL-2 library in a GPL project. It does not seem to state anything regarding using GPL in an MPL-2 project. I haven't found an answer for this anywhere online.

**Comment by ltworf** [comment]
I found this: https://opensource.stackexchange.com/questions/8831/pros-and-cons-of-using-mpl-2-0-license

It seems that they are compatible, both being copyleft and all, but the MPL files must be available also under GPL (which is more restrictive, so should be no problem)

**Comment by ltworf** [comment]
Does my answer satisfy you or this is still open?

**Comment by d3dave** [comment]
Yes, I have decided against using typedload and going for an alternative.

**Comment by ltworf** [comment]
We are no longer in 2018, there are tens of clones now.
