### ISSUE TITLE
date and datetime support

### ISSUE THREAD

**Issue by marlonjan** [ltworf/typedload#66]
Great library, thanks for creating and sharing it!

I wanted to report that I had problems when using it with dates and datetimes:

```
from datetime import date
from typing import NamedTuple

import typedload

class Point(NamedTuple):
    x: float
    y: float
    created_at: date

print(
    typedload.dump(
        Point(x=5.0, y=6.0, created_at=date(2019, 1, 1))
    )
)
```
It crashes with:
```
    raise TypedloadValueError('Unable to dump %s' % value, value=value)
typedload.exceptions.TypedloadValueError: Unable to dump 2019-01-01
Value: 2019-01-01
Type: None
```

Not sure if this is a bug, a feature, or simply not implemented yet.

**Comment by ltworf** [comment]
It is not implemented, I don't know if I will ever implement it, but there are handlers to do this sort of things.

```python3

dumper = typedload.datadumper.Dumper() # Create a Dumper object, so we can modify it

# Let's add a new type handler to the object, so it can handle one more type
dumper.handlers.append(
    (
        lambda x: isinstance(x, datetime.date), # Function that matches the type
        lambda self, value: repr(value), # Function that does something with the value
    )
)

print(
    dumper.dump( # Dump using the custom Dumper object
        Point(x=5.0, y=6.0, created_at=date(2019, 1, 1))
    )
)
```

I used `repr()` to do the dump, but you can replace it with whatever you like.

Be warned that loading this thing back might be complicated. Do you need to do that?

**Comment by ltworf** [comment]
Dumping the date object as a date object rather than converting it to string would work as well I guess.

```python3

dumper = typedload.datadumper.Dumper() # Create a Dumper object, so we can modify it
dumper.basictypes.add(datetime.date) # Add datetime.date to the set of types that do no action.

print(
    dumper.dump( # Dump using the custom Dumper object
        Point(x=5.0, y=6.0, created_at=date(2019, 1, 1))
    )
)

# Now it is trivial to load
loader=typedload.dataloader.Loader()
loader.basictypes.add(datetime.date)
loader.load(Point(x=5.0, y=6.0, created_at=date(2019, 1, 1)), Point)
```

The disadvantage of this method is that you can't serialize to json. Which is why the type isn't added by default in the 1st place.

**Comment by marlonjan** [comment]
Thanks for your quick reply, @ltworf! 

 > Be warned that loading this thing back might be complicated. Do you need to do that?
Yes, it's going to be used both ways, to JSON and back to NamedTuple.

I realized that support for Python dataclasses is increasing quickly. In my project I can replace all the NamedTuples by dataclasses, then tools like pydantic or marshmallow-dataclass should to the job.

**Comment by ltworf** [comment]
Well this project supports dataclasses as well.

**Comment by ltworf** [comment]
There… now that I implemented it I might as well add support :D

```python3

import datetime
import dataclasses

import typedload
import typedload.dataloader
import typedload.datadumper


dumper = typedload.datadumper.Dumper()
dumper.handlers.append(
    (
        lambda x: isinstance(x, datetime.date),
        lambda self, value: (value.year, value.month, value.day),
    )
)

loader.handlers.append(
    (
        lambda x: x == datetime.date,
        lambda self, value, type_: datetime.date(*value),
    )
)


@dataclasses.dataclass
class Pino:
    pino: datetime.date

t = Pino(datetime.date(2019, 1, 1))
dump = dumper.dump(t)
assert loader.load(dump, Pino) == t
```

**Comment by thomascellerier** [comment]
Hurray :)

**Comment by ltworf** [comment]
Maybe you want to review it then? :P
