### ISSUE TITLE
Support running with from __future__ import annotations 

### ISSUE THREAD

**Issue by ltworf** [ltworf/typedload#75]
Having that will cause everything to fail. It looks like I want to support it.

**Comment by ltworf** [comment]
It's an incompatible feature they will introduce in python 4. I won't worry about it for now.

**Comment by CommanderPrS** [comment]
@ltworf 

> Having that will cause everything to fail. It looks like I want to support it.

Yep, `typedload.load()` fails in all sorts of miserable ways when `from __future__ import annotations` is used - tried and confirmed :)

> It's an incompatible feature they will introduce in python 4.

This is not exactly true. The delayed annotation evaluation will be the default behavior in Python 4. The `from __future__ import annotations` thing is supposed to be used in Python 3.7 (and up) to turn on delayed annotations before Python 4 is released. The purpose of this is to reduce the startup time, which is not a joke for large Python projects.

PEP 563 describes all that:

https://www.python.org/dev/peps/pep-0563/

The good news is that, if one were to believe PEP 563, supporting delayed annotations is supposed to be as easy as calling `typing.get_type_hints(obj, globalns=None, localns=None)` when type annotations are needed at run time.

> I won't worry about it for now.

Given the above, you may want to reconsider this statement ;)

**Comment by ltworf** [comment]
The get hints doesn't really work, because I call it in a completely different scope.
