### ISSUE TITLE
null values in JSON are not handled gracefully by load()

### ISSUE THREAD

**Issue by CommanderPrS** [ltworf/typedload#79]
If a field is defined as a compound type, e.g. `List[T]` or `Dict[str,T]`, but the JSON contents specifies `null` as the value for the entire field, `typedload.load(...)` should detect that explicitly and generate an error along the lines of `"null can not be converted to ..."`. The current behavior generates confusing errors (see below, I only checked lists and dictionaries).

## For `List[T]` ##

The actual error thrown:
`AssertionError()`

What really happens is that `enumerate(...)` can not be called on a `None` object here:

```
Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\typedload\dataloader.py", line 216, in load
    return func(self, value, type_)
  File "c:\program files\python37\lib\site-packages\typedload\dataloader.py", line 273, in _listload
    return [l.load(v, t, annotation=Annotation(AnnotationType.INDEX, i)) for i, v in enumerate(value)]
TypeError: 'NoneType' object is not iterable
```

## For `Dict[str,T]` ##

The actual error thrown:
`TypedloadAttributeError("'NoneType' object has no attribute 'items'")`

What really happens is that `.items()` can not be called on a `None` object here:

```
Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\typedload\dataloader.py", line 286, in _dictload
    for k, v in value.items()}
  File "c:\program files\python37\lib\site-packages\typedload\dataloader.py", line 286, in <dictcomp>
    for k, v in value.items()}
  File "c:\program files\python37\lib\site-packages\typedload\dataloader.py", line 220, in load
    raise e
  File "c:\program files\python37\lib\site-packages\typedload\dataloader.py", line 216, in load
    return func(self, value, type_)
  File "c:\program files\python37\lib\site-packages\typedload\dataloader.py", line 288, in _dictload
    raise TypedloadAttributeError(str(e), type_=type_, value=value)
typedload.exceptions.TypedloadAttributeError: 'NoneType' object has no attribute 'items'
Value: None
Type: typing.Dict[str, typing.List[str]]

Load trace:
Type: typing.Dict[str, typing.List[str]] Annotation: (AnnotationType.VALUE None) Value: None
Path: 
```

**Comment by ltworf** [comment]
Thanks for your report.

The assert is there to make sure that all the raised exceptions are of `TypedloadException` and find bugs if they aren't, so at least the assert is working :D

I'll need to make them generate the proper exceptions.

**Comment by CommanderPrS** [comment]
@ltworf 

> The assert is there to make sure that all the raised exceptions are of TypedloadException and find bugs if they aren't, so at least the assert is working :D

Yep, that is exactly what happens :) The code in `_listload()` tries to call `enumerate(None)`, which obviously throws the `TypeError` exception. Then the `try`/`except` block up the stack catches it and asserts that it is not `TypedloadException`.

The code in `_dictload()` has its own `try`/`except` block, but, as far as I can tell, it exists for a completely different reason. It just so happens that trying to call `None.items()` throws the same `AttributeError` it expects, so it gets converted to `TypedloadException` - hence no assert up the stack.

**Comment by ltworf** [comment]
Converting it to a subclass of a `TypedloadException` is what I want, since it carries information on where the problem happened in the data tree, the list one is worse.

**Comment by ltworf** [comment]
I am working on it but it broke tests so I have to investigate it better.
